import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { barlow } from "./utils/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" className={`${barlow.variable} bg-gray-800`}>
      <body>{children}</body>
    </html>
  );
}
