import "./globals.css";
import { barlow } from "./utils/fonts";
// import { Barlow } from "next/font/google";

// const barlow = Barlow({
//   weight: ["400", "500", "600", "700"],
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${barlow.className} bg-gray-800`}>
      <body>{children}</body>
    </html>
  );
}
